name: rundfunk
base: core18
version: '2.1.2'
summary: Unofficial Deutschlandradio GNU/Linux client
description: |
  Unofficial Deutschlandradio GNU/Linux client for the Deutschlandradio channels, Deutschlandfunk, Deutschlandfunk
  Kultur, Deutschlandfunk Nova and Dokumente und Debatten.

grade: stable
confinement: strict

apps:
  rundfunk:
    environment:
      PYTHONPATH: $SNAP
    command: python3 $SNAP/src/main.py
    extensions: [ gnome-3-28 ]
    plugs:
      - audio-playback
      - network
    slots:
      - mpris

parts:
  copy-src:
    plugin: dump
    source: ./src
    organize:
      '*' : src/
  rundfunk:
    plugin: python
    python-version: python3
    python-packages:
      - pydbus>=0.6.0, <0.7.0
    stage-packages:
      - python3-gst-1.0
      - gir1.2-appindicator3-0.1
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - libgpm2
      - libslang2
